### PR TITLE
hero section

### PR DESCRIPTION
**Pull request by odunayo222**

### CODE REVIEW

**Comment by odunayo222** [comment]
hero section

**Comment by Girlscoding-ng** [comment]
heroBanner

**Comment by Girlscoding-ng** [comment]
Use that image I created let's see how it looks

**Comment by Girlscoding-ng** [comment]
So the hero section will have the image and the text been flexed with a white background

**Comment by Girlscoding-ng** [comment]
make the hero text look like this
ss5
 then add "Put a smile on the less privilege" with the font-size reduced under the hero-text

**Comment by Girlscoding-ng** [comment]
ss6
Make the button like this

**Pull request closed without merging**
